api_version: 3
name: nvflare_local_project
description: NVIDIA FLARE sample yaml for example project
builders:
- args:
    template_file:
    - master_template.yml
    - aws_template.yml
    - azure_template.yml
  path: nvflare.lighter.impl.workspace.WorkspaceBuilder
- path: nvflare.lighter.impl.template.TemplateBuilder
- args:
    config_folder: config
    overseer_agent:
      args:
        sp_end_point: server_ip:port1:port2
      overseer_exists: false
      path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
  path: nvflare.lighter.impl.static_file.StaticFileBuilder
- path: nvflare.lighter.impl.cert.CertBuilder
- path: nvflare.lighter.impl.signature.SignatureBuilder
description: NVIDIA FLARE sample project yaml file
name: nvflare_local_simulation
participants:
- admin_port: port2
  fed_learn_port: port1
  name: server_ip
  org: nvidia
  type: server

- name: admin@nvidia.com
  org: nvidia
  role: project_admin
  type: admin

- name: zgt_1
  org: nvidia
  type: client

- name: ntnu_1
  org: nvidia
  type: client